# Generated by Django 4.2.1 on 2023-05-16 09:37

import admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_school_name', models.CharField(max_length=100)),
                ('current_school_address', models.CharField(max_length=200)),
                ('current_school_city', models.CharField(max_length=100)),
                ('current_school_state_province', models.CharField(max_length=100)),
                ('current_school_postal_code', models.CharField(max_length=20)),
                ('current_school_country', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('dates_attended', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(default='Not Set', max_length=150)),
                ('city', models.CharField(default='Not Set', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('post_code', models.BigIntegerField()),
                ('phone_number', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_admissionapplication', models.DateField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, upload_to=admission.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField()),
                ('signature_applicant', models.CharField(max_length=100)),
                ('date_signed', models.DateField()),
                ('signature_parent_guardian', models.CharField(max_length=100)),
                ('date_parent_guardian_signed', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('educational_background', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.educationalbackground')),
                ('emergency_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.emergencycontact')),
                ('guardian1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian1', to='admission.parentguardian')),
                ('guardian2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian2', to='admission.parentguardian')),
                ('personal_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.personalinformation')),
            ],
        ),
    ]
