# Generated by Django 4.2.1 on 2023-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='admission_no',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
