# Generated by Django 4.2.1 on 2023-05-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='personal_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_form', to='admission.studentpersonalinformation'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='personal_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_background', to='admission.studentpersonalinformation'),
        ),
    ]
