# Generated by Django 4.2.1 on 2023-05-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_personalinformation_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='admission.personalinformation')),
            ],
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='date_parent_guardian_signed',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='guardian1',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='guardian2',
        ),
        migrations.DeleteModel(
            name='ParentGuardian',
        ),
    ]
