# Generated by Django 2.1 on 2018-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Not Set', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_phone_no',
            field=models.CharField(default='0000000', max_length=11),
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_proffesion',
            field=models.CharField(default='Not Set', max_length=50),
        ),
    ]
