# Generated by Django 2.1 on 2018-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180819_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_admision',
            field=models.DateField(auto_now=True),
        ),
    ]
