# Generated by Django 2.1 on 2018-08-20 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0003_student_date_of_admision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_admision',
            new_name='date_of_admission',
        ),
    ]
