# Generated by Django 2.1 on 2018-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0004_auto_20180820_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(),
        ),
    ]
