# Generated by Django 2.1 on 2018-08-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0005_auto_20180820_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
