# Generated by Django 2.1 on 2018-08-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0002_course_course_description'),
        ('students', '0007_student_is_studying'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
