# Generated by Django 2.1 on 2018-08-24 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0010_auto_20180824_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='month',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
