# Generated by Django 2.1 on 2018-08-24 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentfee_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='year',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
