# Generated by Django 2.1 on 2018-08-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0013_auto_20180824_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
