# Generated by Django 2.1 on 2018-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0015_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='month',
            field=models.CharField(
                choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'),
                         ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'),
                         ('11', 'November'), ('12', 'December')], max_length=2),
        ),
    ]
