# Generated by Django 2.1 on 2018-09-30 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0016_auto_20180905_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Fee Summary',
                'verbose_name_plural': 'Fee Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('students.studentfee',),
        ),
    ]
