# Generated by Django 2.1 on 2018-10-02 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20181001_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('display_name', models.CharField(max_length=50, verbose_name='Displayed Name')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('display_name', models.CharField(max_length=50, verbose_name='Displayed Name')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeeSummary',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='date',
        ),
        migrations.AddField(
            model_name='studentfee',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2018, 11, 1), verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Student'),
        ),
        migrations.AddField(
            model_name='feegroup',
            name='fee_types',
            field=models.ManyToManyField(null=True, to='students.FeeType'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.FeeGroup'),
        ),
    ]
