# Generated by Django 2.1 on 2018-10-01 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20181001_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 21, 49, 12, 954914, tzinfo=utc)),
        ),
    ]
