# Generated by Django 2.2.3 on 2019-10-15 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20190705_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2019, 11, 1), verbose_name='Valid Until'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('social_security_number', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='0000000', max_length=11)),
                ('profession', models.CharField(default='Not Set', max_length=50)),
                ('relation_to_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Student')),
            ],
        ),
    ]
