# Generated by Django 2.1 on 2018-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
