# Generated by Django 2.1 on 2018-09-27 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0003_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
