# Generated by Django 2.1 on 2018-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_studying',
            field=models.BooleanField(default=True),
        ),
    ]
